version: '3.8'

services:
  # NGINX как reverse proxy
  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - user-service
      - order-service
    networks:
      - microservices-network
    restart: unless-stopped

  # User Service
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5001:5000"
    networks:
      - microservices-network
    restart: unless-stopped

  # Order Service
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "5002:5000"
    networks:
      - microservices-network
    restart: unless-stopped

# Определяем сеть
networks:
  microservices-network:
    driver: bridge